conf/urls.py
from django.contrib import admin
from django.urls import path,include
from core.views import index



urlpatterns = [
    path('', index, name='produto'), 
    # path('produto/', include('produto.urls', namespace='produto')), 
    path('produto/', include(('produto.urls', 'produto'), namespace='produto')),
    path('entrada/', include('entrada.urls', namespace='entrada')), 
    path('saida/', include('saida.urls', namespace='saida')),
]

path('admin/', admin.site.urls),

saida/urls.py
from django.urls import path
from .views import list_saida, new_saida, update_saida, delete_saida

app_name = 'saida'

urlpatterns = [
    path('list_saida/', list_saida, name='list_saida'),
    path('new_saida/', new_saida, name='new_saida'),
    path('update_saida/<int:pk>/', update_saida,name='update_saida'),
    path('delete_saida/<int:pk>/', delete_saida,name='delete_saida'),
    ]

saida/models.py
from django.db import models
from produto.models import Produtos

class Saidas(models.Model):
    produto = models.ForeignKey(Produtos, on_delete=models.CASCADE, verbose_name='Produto')
    preco = models.FloatField('Preço', default=0)
    quantidade = models.IntegerField('Quantidade', default=0)
    criado = models.DateTimeField('Criado em', auto_now_add=True)
    modificado = models.DateTimeField('Modificado em', auto_now=True)

saida/forms.py
from django import forms
from .models import Saidas

class SaidaForm(forms.ModelForm):
    class Meta:
        model = Saidas
        fields = ['produto', 'quantidade', 'preco']

    def clean_quantidade(self):
        qtd = self.cleaned_data.get('quantidade')
        produto = self.cleaned_data.get('produto')

        if self.instance.pk:
            qtd_antiga = self.instance.quantidade
            disponivel = produto.quantidade + qtd_antiga
        else:
            disponivel = produto.quantidade

        if qtd > disponivel:
            raise forms.ValidationError(
                f'Voce so tem {disponivel} unidades disponiveis no estoque.'
            )
        return qtd


       

saida/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Saidas
from .forms import SaidaForm

def list_saida(request):
    saidas = Saidas.objects.all()
    template_name = 'list_saida.html'
    context = {
        'saidas': saidas,
        }
    return render(request, template_name, context)

def new_saida(request):
    if request.method == 'POST':
        form = SaidaForm(request.POST)
        if form.is_valid():
            form.save(commit=False)
            form.cleaned_data['produto'].quantidade = form.cleaned_data['produto'].quantidade - form.cleaned_data['quantidade']
            form.cleaned_data['produto'].preco = form.cleaned_data['preco']
        
            form.cleaned_data['produto'].save_base()
            form.save()
            return redirect('saida:list_saida')
    
    else:
        form = SaidaForm()

    return render(request, 'new_saida.html', {'form': form})
    
def update_saida(request, pk):
    saida = get_object_or_404(Saidas, pk=pk)
    # saida = Saidas.objects.get(pk=pk)
    qtd_antiga = saida.quantidade

    print('==> ', qtd_antiga)
    if request.method == 'POST':
        form = SaidaForm(request.POST, instance=saida)

        if form.is_valid():
            produto = form.cleaned_data['produto']
            nova_qtd = form.cleaned_data['quantidade']
            disponivel = produto.quantidade + qtd_antiga

            if nova_qtd > disponivel:
                form.add_error('quantidade', 
                                f'So ha disponivel {disponivel} unidades no estoque.'
                    )
            
            else:
                produto.quantidade = disponivel - nova_qtd
                produto.preco = form.cleaned_data['preco']
                produto.save()
                form.save()
                return redirect('saida:list_saida')
    else:
        form = SaidaForm(instance=saida)    
    
    return render(request, 'update_saida.html', 
            {
                'form': form,
                'pk': pk,
            })
    
def delete_saida(request, pk):
    saida = Saidas.objects.get(pk=pk)
    saida.produto.quantidade = saida.produto.quantidade + saida.quantidade
    saida.produto.save()
    saida.delete()
    return redirect('saida:list_saida')

saida/templates/list_saida.html
{% extends 'base.html' %}
{% block product %}
<p>Saida</p>
<a class="button is-primary" href="{% url 'saida:new_saida' %}">Novo</a>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Produto</th>
            <th>Preço</th>
            <th>Quantidade</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for saida in saidas %}
        <tr>
            <th>{{ saida.id }}</th>
            <td>{{ saida.produto }}</td>
            <td>{{ saida.preco }}</td>
            <td>{{ saida.quantidade }}</td>
            <td><a class="button is-primary" href="{% url 'saida:update_saida' saida.id %}">alterar</a></td>
            <td><a class="button is-primary" href="{% url 'saida:delete_saida' saida.id %}">deletar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

saida/templates/new_saida.html
{% extends 'base.html' %}
{% block product %}
<p>Nova Saida</p>
<form action="{% url 'saida:new_saida' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button is-primary" type="submit">salvar</button>
</form>
{% endblock %}

saida/templates/update_saida.html
{% extends 'base.html' %}
{% block product %}
<p>Alterar saida</p>
<form action="{% url 'saida:update_saida' pk %}" method="post">
    {% csrf_token %}

    {% if form.non_field_errors %}
        <div class="notification is-danger">
            {{ form.non_field_errors }}
        </div>
    {% endif %}


    {{ form.as_p }}
    <button class="button is-primary" type="submit">Salvar</button>
</form>
{% endblock %}